controller:
  simple_chassis_controller:
    type: simple_chassis_controller/SimpleChassisController
    wheel_track: 0.362
    wheel_base: 0.362

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50